### ISSUE TITLE
Dictionaries inside /content are blocked by default

### ISSUE THREAD

**Issue by kwin** [orbinson/aem-dictionary-translator#27]
Since https://issues.apache.org/jira/browse/SLING-11744 the default configuration blocks dictionaries outside `/apps` and `/libs` for security reasons (https://nvd.nist.gov/vuln/detail/CVE-2023-25621). How do you circumvent this without compromising security?

**Comment by kwin** [comment]
In fact on a recent AEMaaCS server I see the following configuration

```
{
        "pid": "org.apache.sling.i18n.impl.JcrResourceBundleProvider",
        "properties": {
          "included.paths": [
            "/libs",
            "/apps",
            "/content/forms/af",
            "/content/dam/formsanddocuments"
          ],
          "preload.bundles": true,
          "resource.paths": [
            ".",
            "/content"
          ]
        }
},
```

So nothing is loaded from /content except for some repository areas.

**Comment by royteeuwen** [comment]
@kwin  I'll update the docs, because indeed, in the projects we use this we actually explicitly set that OSGi config ourselves and we set it to allow `/content/dictionaries` as path for creating dictionaries.

Thanks for that CVE, I wasn't aware of that one, but seeing as AEM Forms also still allows editing of labels (/content/forms/af), I don't see how we make the issue bigger with this UI ;). We at least don't have a fix for this, besides setting permissions on `/content/dictionaries` to a subset of authors that are the real webmasters. 

Do you have any alternatives / suggestions? We'd have to update sling i18n if we'd need more control but then also AEM as product would have to be updated with those changes. Making the basename or other kind of properties more restrictive on where the labels can be loaded / used would for example be something that could be looked at

**Comment by kwin** [comment]
> I don't see how we make the issue bigger with this UI ;).

I agree, but I fear that soon (tm) the forms dictionaries will be moved to /libs and by default no dictionaries are allowed in /content by default.

**Comment by kwin** [comment]
@royteeuwen Does the UI work fine, even if the dictionary in that location is not included in the `JcrResourceBundleProvider` OSGi config? We are thinking about streamlining the process of translations with some UI (even if changes are not instant that way).

**Comment by royteeuwen** [comment]
Yes, the UI works fine, we are actively using this at clients. But the dictionary will of course not be loaded into the `ResourceBundle` if you don't provide the `JcrResourceBundleProvider` OSGi config... 

What are you thinking about? How would you use it if it isnt through the existing i18n api's?

In any case, if Adobe would close down the OSGi config, they would first scan existing clients and see if it is used. Then they would find all our clients and would have to start putting it in the deprecation list, which would typically take a year or more to enforce, if ever...

FYI, we actually use the i18n dictionaries coming from /content/dictionaries within [Contextual Content Variables](https://adobe-consulting-services.github.io/acs-aem-commons/features/contextual-content-variables/index.html) from ACS Commons, where you can then type (( dictionary.myLabelName )) inline in your text. I could see if we can open-source that specific part as well, and if they would ever close down the JcrResourceBundleProvider, we could easily change it to use another way of loading from /content/dictionaries

**Comment by kwin** [comment]
> What are you thinking about? How would you use it if it isnt through the existing i18n api's?

We are currently thinking to just use the tool to allow maintenance of a shadow dictionary (where changes are not immediately active, but only after review and merge back to `/apps`)

**Comment by royteeuwen** [comment]
I have updated the readme to mention the required OSGi config, closing this issue. As mentioned, we actively use this in AEMaaCS and as long as Adobe doesn't explicitly deprecates it, we will keep on using it this way

**Comment by kwin** [comment]
Thanks, much appreciated.
